<a href="https://colab.research.google.com/github/Molly-12/Base-class/blob/main/TensorFlowbasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
a=1.2  #create a scalar in python
aa=tf.constant(1.2)  #create a scalar in tensorflow
type(a),type(aa),tf.is_tensor(aa)
tf.is_tensor(a)
x=tf.constant([1,2,3.3])
x
x.numpy()
b=tf.constant([1.2])
b
b.shape


TensorShape([1])

In [ ]:
a=tf.constant([1.2,3.2])
a
a.shape

TensorShape([2])

In [ ]:
a=tf.constant([[1,2],[3,4]])
a
#a.shape

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
a=tf.constant([[1.2,3.2,4.1],[4.5,3.2,1.5],[2.1,3.2,4.3]])
a

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1.2, 3.2, 4.1],
       [4.5, 3.2, 1.5],
       [2.1, 3.2, 4.3]], dtype=float32)>

In [ ]:
a=tf.constant('hello ,deep learning')
a

<tf.Tensor: shape=(), dtype=string, numpy=b'hello ,deep learning'>

In [ ]:
import tensorflow as tf
a=tf.constant('Hello, Deep Learning')
tf.strings.lower(a)
tf.strings.length(a)
tf.strings.upper(a)
tf.strings.split('hello world').numpy()
a=tf.constant('Hello')
b=tf.constant('world')
tf.strings.join([a,b]).numpy()


b'Helloworld'

In [ ]:
import tensorflow as tf
a=tf.constant('True')
b=tf.constant([True,False])
a is True
#a=True
#a == True

In [ ]:


a=tf.constant(0)
a
a is True
a=tf.constant('Yes')
a
a is True

False

In [ ]:
a="Yes"
print(type(a))
b=0
type(b)

<class 'str'>


int

In [ ]:
import numpy as np
a=tf.constant(np.pi,dtype=tf.float16)
a

<tf.Tensor: shape=(), dtype=float16, numpy=3.14>

In [ ]:
import numpy as np
a=tf.constant(np.pi,dtype=tf.float32)
a
a=tf.constant(np.pi,dtype=tf.float64)
a

<tf.Tensor: shape=(), dtype=float64, numpy=3.141592653589793>

In [ ]:
tf.constant(123456789,dtype=tf.int16)
tf.constant(123456789,dtype=tf.int32)
tf.constant(123456789,dtype=tf.int64)


<tf.Tensor: shape=(), dtype=int64, numpy=123456789>

For most deep learning algos, int 32 and float 32 are able to generate the output 
wheras some algos which require higher accuracy, such as reinforcement learning we use tf.int64 and tf.float64

In [ ]:
a=tf.constant(3.14,dtype=tf.float16)
print('before:',a.dtype)
if a.dtype!=tf.float32:
  a=tf.cast(a,tf.float32)
print('after:',a.dtype)


before: <dtype: 'float16'>
after: <dtype: 'float32'>


In [ ]:
a=tf.constant(12356789,dtype=tf.int32)
print('before:',a.dtype)
if a.dtype!=tf.int16:
  a=tf.cast(a,tf.int16)
a


before: <dtype: 'int32'>


<tf.Tensor: shape=(), dtype=int16, numpy=-29515>

In [ ]:
a=tf.constant([True,False])
tf.cast(a,tf.int32)


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 0], dtype=int32)>

In [ ]:
a=tf.constant(True)
tf.cast(a,tf.int32)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
a=tf.constant([1,2,3])
tf.cast(a,tf.float16)

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([1., 2., 3.], dtype=float16)>

In [ ]:
a=tf.constant(1.24)
tf.cast(a,tf.int16)

<tf.Tensor: shape=(), dtype=int16, numpy=1>

In [ ]:
a=tf.constant([0,1,-2,-3,4])
tf.cast(a,tf.bool)        #0 is false and rest all are true(incluidng negative no)

<tf.Tensor: shape=(5,), dtype=bool, numpy=array([False,  True,  True,  True,  True])>

In [ ]:
import tensorflow as tf
a=tf.Variable([[1.0,2.0],[1.0,2.0]])
a.assign(([[2,100],[1,10]]))
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[  2., 100.],
       [  1.,  10.]], dtype=float32)>


In [ ]:
b=tf.Variable([5])
c=tf.Variable([[1,2],[3,4]])
print(b*c)

tf.Tensor(
[[ 5 10]
 [15 20]], shape=(2, 2), dtype=int32)


In [ ]:
tf.convert_to_tensor([1,2.])


<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [ ]:
import numpy as np
tf.convert_to_tensor(np.array([[1,2.],[3,4]]))

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1., 2.],
       [3., 4.]])>

In [ ]:
tf.zeros([]),tf.ones([])

(<tf.Tensor: shape=(), dtype=float32, numpy=0.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.0>)

In [ ]:
tf.zeros([1]),tf.ones([1])

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>)

In [ ]:
tf.zeros([2,2]) # creating a matrix of 2x2 of all 0's.

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [ ]:
tf.ones([3,2])

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [ ]:
tf.ones([3,2],dtype=tf.float64)

<tf.Tensor: shape=(3, 2), dtype=float64, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]])>

Creating numeric tensors


In [ ]:
tf.fill([],-1)

<tf.Tensor: shape=(), dtype=int32, numpy=-1>

In [ ]:
tf.fill([1],-1)

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([-1], dtype=int32)>

In [ ]:
tf.fill([2],2)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 2], dtype=int32)>

In [ ]:
tf.fill([2,2],2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 2],
       [2, 2]], dtype=int32)>

In [ ]:
tf.fill([2,2],99)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[99, 99],
       [99, 99]], dtype=int32)>

In [ ]:
tf.random.normal([2,2])


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.19558786, -1.635005  ],
       [ 2.0228457 ,  0.12890038]], dtype=float32)>

In [ ]:
tf.random.normal([2,2],mean=1,stddev=2)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 4.2800274, -1.1837671],
       [ 1.3474326,  2.0878847]], dtype=float32)>

In [ ]:
tf.random.uniform([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.2818812 , 0.67332935],
       [0.93998635, 0.11103761]], dtype=float32)>

In [ ]:
tf.random.uniform([2,2],maxval=10)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[9.729098 , 6.970408 ],
       [9.756299 , 1.0274851]], dtype=float32)>

In [ ]:
tf.random.uniform([2,2],maxval=100,dtype=tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12,  5],
       [59, 29]], dtype=int32)>

In [ ]:
tf.random.uniform([2,2],maxval=100)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[96.30023  , 60.554813 ],
       [53.15397  ,  7.4817657]], dtype=float32)>

In [ ]:
tf.range(10)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.range(1,10,delta=2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9], dtype=int32)>

Indexing and Slicing

In [ ]:
x=tf.random.normal([4,32,32,3])
x[0]

<tf.Tensor: shape=(32, 32, 3), dtype=float32, numpy=
array([[[-0.8701544 ,  1.2833066 ,  1.1377617 ],
        [ 0.14048354,  2.3595905 ,  0.5554954 ],
        [-1.3196203 ,  0.2663512 , -1.0404919 ],
        ...,
        [ 0.6966038 , -1.2372326 , -1.3729875 ],
        [ 0.40439934,  0.23972948, -1.0380127 ],
        [ 0.3134793 ,  0.4276842 , -0.10513584]],

       [[-2.5798037 ,  1.7464912 ,  0.9468667 ],
        [-0.59424305,  0.5363449 ,  0.6521623 ],
        [ 0.6955014 ,  0.18617013,  0.48685762],
        ...,
        [ 0.24164727,  1.2312559 ,  1.6454687 ],
        [ 0.04367115,  1.2646289 , -1.083509  ],
        [ 1.6149625 , -0.45746788, -3.1498973 ]],

       [[ 0.2593459 ,  1.635259  ,  0.15814465],
        [-2.5442653 ,  1.0671363 , -1.5809457 ],
        [-0.22457187,  0.6179545 , -0.76597744],
        ...,
        [ 1.5955565 , -0.2143915 , -2.3261683 ],
        [ 1.5144174 , -1.1107515 ,  1.345317  ],
        [-0.5082988 , -0.38265923, -0.3688124 ]],

       ...,

       

In [ ]:
x=tf.random.normal([4,32,32,3])
x[1]

<tf.Tensor: shape=(32, 32, 3), dtype=float32, numpy=
array([[[-0.1925303 ,  1.6747046 , -0.61304957],
        [ 0.9406548 ,  0.67051446, -0.16465564],
        [ 1.2573606 ,  1.8596889 ,  0.33751196],
        ...,
        [ 1.088775  ,  0.50186026, -1.1730535 ],
        [-1.2109039 ,  1.7291212 , -1.4971735 ],
        [-0.6728097 , -3.3095968 , -0.4895693 ]],

       [[-0.23502086, -0.11487722,  0.24762994],
        [ 1.1232882 , -0.2747242 , -0.06298511],
        [-2.352914  ,  0.96855664,  1.341723  ],
        ...,
        [-1.4478756 ,  0.8743116 , -1.3586259 ],
        [-0.18649323, -0.39442903, -0.92430365],
        [ 0.47399172, -0.8889191 , -0.83840305]],

       [[ 0.49662676,  0.18360959, -0.75106484],
        [-0.2725235 , -0.54247975,  0.96976024],
        [-1.3146994 , -1.4452043 , -0.05575434],
        ...,
        [ 0.8955091 ,  0.5491541 , -1.9071729 ],
        [-0.57128906, -0.03882982,  0.40236202],
        [-0.4910373 ,  0.6385085 , -0.14613539]],

       ...,

       

In [ ]:
x=tf.random.normal([4,32,32,3])
x[0][1]

<tf.Tensor: shape=(32, 3), dtype=float32, numpy=
array([[ 3.72244745e-01, -6.31459951e-01,  1.17314547e-01],
       [-1.84556931e-01, -2.94705480e-01,  8.14172179e-02],
       [ 7.12198377e-01,  5.34317315e-01, -2.57494934e-02],
       [-1.60056561e-01, -4.33525406e-02, -7.27715254e-01],
       [-7.77756155e-01,  1.00419986e+00, -6.44791782e-01],
       [-1.21942949e+00,  2.50083041e+00, -2.23358244e-01],
       [-1.02152812e+00, -1.67015445e+00, -1.26943088e+00],
       [-1.07354641e+00, -4.41025078e-01,  1.44125688e+00],
       [ 1.18816450e-01, -4.44720477e-01, -2.07235289e+00],
       [-7.87509322e-01, -7.58307695e-01,  3.58920395e-01],
       [-3.55183035e-01, -2.67273903e-01, -5.28775342e-02],
       [ 2.89750427e-01,  5.17805457e-01,  1.88792706e-01],
       [ 9.22376871e-01,  1.28385305e+00, -1.90778973e-03],
       [-2.41513848e-01, -1.22050798e+00,  3.27412099e-01],
       [ 1.73681188e+00,  2.25517601e-01,  1.85430005e-01],
       [-8.62942636e-01,  1.08983243e+00, -8.369087

In [ ]:
x=tf.random.normal([4,32,32,3])
x[0][1][2]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-0.96431535,  0.9024531 ,  0.45584136], dtype=float32)>

In [ ]:
x=tf.random.normal([4,32,32,3])
x[2][1][0][1]

<tf.Tensor: shape=(), dtype=float32, numpy=-0.08645044>

Create a tensor to read 10th row and 3rd column of the second picture

In [ ]:
x=tf.random.normal([4,32,32,3])
x[3][9][2][2]

<tf.Tensor: shape=(), dtype=float32, numpy=0.08261736>

Slicing
syntax: start:end:step  

In [ ]:
import tensorflow as tf
x=tf.random.normal([4,32,32,3])
x[1:3]

<tf.Tensor: shape=(2, 32, 32, 3), dtype=float32, numpy=
array([[[[-1.08320224e+00, -1.15330748e-01, -9.20096815e-01],
         [ 4.07817848e-02, -1.38160205e+00,  6.91386223e-01],
         [ 5.45422018e-01,  5.19378364e-01,  3.14324409e-01],
         ...,
         [ 8.53947759e-01, -6.04954250e-02, -9.58547711e-01],
         [-7.30154932e-01,  1.50402427e+00, -2.62546033e-01],
         [ 8.70101869e-01, -2.39686847e-01,  8.55261266e-01]],

        [[ 3.22100446e-02,  3.94772440e-01,  1.53321788e-01],
         [-1.20723879e+00,  1.86093468e-02,  4.13089603e-01],
         [ 1.13762319e+00,  5.90176344e-01,  4.70529526e-01],
         ...,
         [-3.25432676e-03,  2.07828116e+00,  1.52709198e+00],
         [-1.19471204e+00,  1.05106068e+00,  4.28570479e-01],
         [-1.23765361e+00, -6.70334339e-01, -7.78103709e-01]],

        [[-1.59512892e-01,  3.32617223e-01,  1.86516523e+00],
         [-7.03055501e-01, -8.03879023e-01,  6.34436309e-01],
         [-2.14963007e+00,  1.17525153e-01, 

In [ ]:
x=tf.random.normal([4,32,32,3])
x[0,::]

<tf.Tensor: shape=(32, 32, 3), dtype=float32, numpy=
array([[[ 0.9139279 ,  0.49293888, -1.349947  ],
        [-0.47305283,  0.16670093,  0.7181285 ],
        [-0.459333  , -0.17896004, -0.8330417 ],
        ...,
        [-0.6327839 , -1.0380926 ,  1.2607622 ],
        [-0.7844882 ,  1.6309377 ,  0.50956273],
        [-0.36178234, -0.73823816, -1.0555497 ]],

       [[-0.7359524 , -0.92602605, -0.96089727],
        [-1.6226597 , -0.7177817 ,  0.26107907],
        [ 0.3060612 , -1.4467783 , -0.39154238],
        ...,
        [-1.2086765 , -1.4179325 ,  0.26580718],
        [ 0.3837993 , -1.2439343 ,  0.09095386],
        [-1.187952  , -0.3468991 ,  0.17953314]],

       [[ 0.7180021 , -1.4322199 ,  0.9714918 ],
        [ 0.15266684, -0.5712501 , -0.29266387],
        [-1.5350437 , -1.1691097 , -1.0604947 ],
        ...,
        [-0.7492471 ,  0.6666461 , -0.33894983],
        [ 0.94069725, -1.072502  ,  0.36808553],
        [-0.37716624, -0.9105844 ,  1.026638  ]],

       ...,

       

In [ ]:
x[:,0:28:2,0:28:2,:]

<tf.Tensor: shape=(4, 14, 14, 3), dtype=float32, numpy=
array([[[[ 0.9139279 ,  0.49293888, -1.349947  ],
         [-0.459333  , -0.17896004, -0.8330417 ],
         [ 0.63299406, -1.1282283 ,  1.0892706 ],
         ...,
         [-0.9530752 , -0.6362011 ,  0.968319  ],
         [ 0.58302885, -1.386092  , -0.81038266],
         [ 1.0771667 ,  2.2200751 , -0.06876209]],

        [[ 0.7180021 , -1.4322199 ,  0.9714918 ],
         [-1.5350437 , -1.1691097 , -1.0604947 ],
         [-1.9687814 ,  0.14204025,  1.1882153 ],
         ...,
         [-0.7685092 ,  1.3447671 , -1.8516312 ],
         [-1.2761652 , -0.31486225, -0.6599067 ],
         [ 0.5628906 , -0.9314947 ,  0.6751962 ]],

        [[-1.2040703 ,  0.21652403, -1.054773  ],
         [-1.4170268 , -0.571263  ,  0.24594016],
         [ 0.42221302,  0.14229584, -0.19995205],
         ...,
         [-0.3032715 ,  0.73816323, -0.40676397],
         [ 0.2311324 ,  0.11740138,  0.11845592],
         [ 0.4092914 , -1.7611208 ,  2.3393254 ]

In [ ]:
x[0:3,0:20:2,0:24:2,0:2]

<tf.Tensor: shape=(3, 10, 12, 2), dtype=float32, numpy=
array([[[[ 9.13927913e-01,  4.92938876e-01],
         [-4.59333003e-01, -1.78960040e-01],
         [ 6.32994056e-01, -1.12822831e+00],
         [-4.04062957e-01, -4.92092133e-01],
         [ 2.29358390e-01,  8.59771520e-02],
         [ 1.82921207e+00,  2.09781766e+00],
         [ 4.26784545e-01,  3.63395691e-01],
         [ 1.08047448e-01, -8.49628687e-01],
         [-3.31899226e-02, -1.47023749e+00],
         [-6.56070530e-01,  1.68710947e+00],
         [-3.38060856e-01,  4.29333150e-01],
         [-9.53075171e-01, -6.36201084e-01]],

        [[ 7.18002081e-01, -1.43221986e+00],
         [-1.53504372e+00, -1.16910970e+00],
         [-1.96878135e+00,  1.42040253e-01],
         [-8.19939077e-01,  1.56173122e+00],
         [ 6.94826245e-01,  7.41025090e-01],
         [-9.38156009e-01, -4.08118725e-01],
         [-1.36065972e+00,  6.68468356e-01],
         [-7.63846636e-02,  1.79240078e-01],
         [-2.43559331e-01,  2.32691154e-01

In [ ]:
x=tf.range(9)
x[8:0:-1]

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([8, 7, 6, 5, 4, 3, 2, 1], dtype=int32)>

read all channels of each picture ,where both rows and columns are sampled evry 2 elements

In [ ]:
x=tf.random.normal([4,32,32,3])
x[0,::-2,::-2]

<tf.Tensor: shape=(16, 16, 3), dtype=float32, numpy=
array([[[-1.22037733e+00, -3.48806791e-02, -1.55213749e+00],
        [-9.30514991e-01, -1.29556671e-01,  2.03953400e-01],
        [ 1.29111254e+00,  1.33058652e-01,  1.08134425e+00],
        [-2.52154738e-01, -3.26875240e-01, -1.76100826e+00],
        [ 7.55524755e-01, -5.01428425e-01, -1.52195454e+00],
        [ 1.65871426e-01,  3.58347356e-01, -1.61433578e+00],
        [ 6.19912505e-01, -4.26989943e-01,  9.57551956e-01],
        [ 2.35541523e-01,  5.83604455e-01,  5.69348693e-01],
        [ 7.53837824e-01, -3.81722227e-02,  2.22584724e+00],
        [ 9.57415700e-01, -7.56532773e-02,  1.62842047e+00],
        [ 4.42307204e-01, -1.02328134e+00, -3.53571951e-01],
        [ 1.20931673e+00, -1.02278197e+00,  1.49884784e+00],
        [ 4.35349196e-01,  1.00704825e+00,  8.67395997e-01],
        [-1.70633480e-01,  2.54732579e-01,  9.30871069e-01],
        [ 9.89132941e-01,  6.20445609e-01, -7.52358317e-01],
        [-7.45423794e-01, -5.290

In [ ]:
x[:,:,:,1] # read data on green channel

<tf.Tensor: shape=(4, 32, 32), dtype=float32, numpy=
array([[[ 0.08398483, -0.11792978, -0.51617587, ..., -0.5399414 ,
         -0.09782197,  0.6028272 ],
        [-0.46639606, -0.31512785, -0.25173593, ..., -0.41751343,
         -0.29574773,  0.4627305 ],
        [ 1.3933975 , -0.2203321 ,  2.7608397 , ..., -0.96827894,
          0.7072403 ,  0.28363597],
        ...,
        [-0.05285937, -1.4825704 , -1.417369  , ...,  0.68867964,
         -1.9064804 , -2.6869469 ],
        [ 0.8015265 , -1.062452  , -1.7621895 , ...,  0.7359221 ,
         -0.31963882, -1.4342076 ],
        [-0.7168467 , -0.529067  , -0.8795647 , ..., -0.12955667,
          2.5540035 , -0.03488068]],

       [[ 0.10608406,  0.9967606 ,  2.8529296 , ...,  0.49194852,
          0.49149   , -0.17210743],
        [-1.0129123 , -1.1642842 ,  0.12245367, ...,  0.04996784,
         -0.13936736,  0.8033614 ],
        [ 0.8698893 , -0.74341553, -0.2197548 , ...,  0.66471547,
         -0.34854195,  1.4142867 ],
        ...,
 

In [ ]:
x[0:2,...,1:]

<tf.Tensor: shape=(2, 32, 32, 2), dtype=float32, numpy=
array([[[[ 8.39848295e-02,  2.35443044e+00],
         [-1.17929779e-01, -2.02515468e-01],
         [-5.16175866e-01, -2.62967277e+00],
         ...,
         [-5.39941370e-01,  1.23619425e+00],
         [-9.78219733e-02, -2.05171371e+00],
         [ 6.02827191e-01, -4.77976091e-02]],

        [[-4.66396064e-01,  9.60634742e-03],
         [-3.15127850e-01,  5.65695286e-01],
         [-2.51735926e-01,  1.30263650e+00],
         ...,
         [-4.17513430e-01,  1.43498623e+00],
         [-2.95747727e-01, -8.05626869e-01],
         [ 4.62730497e-01, -1.16809130e+00]],

        [[ 1.39339745e+00, -9.37164783e-01],
         [-2.20332101e-01,  1.03986435e-01],
         [ 2.76083970e+00,  2.19916523e-01],
         ...,
         [-9.68278944e-01, -1.26659012e+00],
         [ 7.07240283e-01,  2.53059115e-05],
         [ 2.83635974e-01,  2.92998374e-01]],

        ...,

        [[-5.28593659e-02, -4.41895306e-01],
         [-1.48257041e+00, 

In [ ]:
a=tf.range(5)
b=tf.constant(2);
a//b

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 0, 1, 1, 2], dtype=int32)>

In [ ]:
x=tf.range(4)
tf.pow(x,3)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 0,  1,  8, 27], dtype=int32)>

In [ ]:
x**2

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 4, 9], dtype=int32)>

In [ ]:
x=tf.constant([1.,4.,9.])
x**(0.5)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [ ]:
x=tf.range(5)
x=tf.cast(x,dtype=tf.float32)
tf.sqrt(x)

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([0.       , 1.       , 1.4142135, 1.7320508, 2.       ],
      dtype=float32)>

In [ ]:
x=tf.constant([1.,2.,3.])
2**x

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 4., 8.], dtype=float32)>

In [ ]:
tf.exp(1.)

<tf.Tensor: shape=(), dtype=float32, numpy=2.7182817>

In [ ]:
x=tf.exp(3.)
tf.math.log(x)

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [ ]:
x=tf.constant([1.,2.])
x=10**x
tf.math.log(x)/tf.math.log(10.)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

Concatenation


In [ ]:
a=tf.random.normal([4,35,8])
b=tf.random.normal([6,35,8])
tf.concat([a,b],axis=0)


<tf.Tensor: shape=(10, 35, 8), dtype=float32, numpy=
array([[[-1.9420979e+00,  4.2333609e-01,  1.0014653e+00, ...,
         -1.0837486e+00,  1.2626834e-01,  7.6259419e-02],
        [-9.3955927e-02, -6.0991842e-01,  7.0522034e-01, ...,
         -3.4433988e-01,  2.6344912e+00, -8.7690455e-01],
        [-2.0413764e+00, -9.1358408e-02, -1.2242329e+00, ...,
          6.9234657e-01, -1.0615697e-01, -1.2515664e+00],
        ...,
        [-6.2867075e-01,  3.3950168e-01, -1.1074107e+00, ...,
          1.0479733e+00,  9.7107321e-02, -2.9137105e-01],
        [ 1.8035157e-01,  1.0231512e+00,  2.6538324e+00, ...,
         -3.7440223e-01, -1.1786560e-01, -9.2781687e-01],
        [ 1.4622164e+00,  8.4435470e-02,  5.5334443e-01, ...,
         -5.9396905e-01, -3.4199172e-01,  8.9648098e-01]],

       [[ 1.0281767e+00, -1.2398784e+00,  9.6308482e-01, ...,
         -1.5817909e+00, -3.0218706e-01, -6.2338656e-01],
        [ 1.3870412e+00, -9.3871033e-01,  1.8633291e+00, ...,
          6.7696816e-01, -7.31

In [ ]:
a=tf.random.normal([35,8])
b=tf.random.normal([35,8])
tf.stack([a,b],axis=0)

<tf.Tensor: shape=(2, 35, 8), dtype=float32, numpy=
array([[[-1.1003873 ,  1.2877933 , -0.72074705, -1.329978  ,
         -1.1239352 , -0.18170212, -0.8853451 ,  0.7077851 ],
        [ 0.71084094,  1.5679867 ,  0.8704046 ,  1.0945919 ,
          0.9558945 ,  0.36228704,  1.754889  ,  0.553273  ],
        [-0.22641838, -0.44105482, -0.58985466,  0.7837374 ,
          0.00500652, -1.737932  ,  0.75096256,  0.12307664],
        [-0.566151  , -1.1355826 ,  1.5041041 , -0.15154436,
          0.7200524 , -1.3270793 ,  1.2887243 ,  0.44659668],
        [-0.5104839 ,  1.4437615 ,  0.38009292, -0.8739027 ,
          0.32819718, -0.08525572, -0.5014911 , -0.45994684],
        [ 1.7504052 , -0.0493594 , -0.7569238 ,  1.350527  ,
         -1.118649  , -1.1963584 ,  0.58158654,  0.56715816],
        [-0.7761777 , -0.14290944,  0.43680668, -0.65892637,
         -1.5126667 ,  0.58194363,  0.73617524, -0.53420925],
        [ 0.5253011 ,  0.0322157 ,  0.42843223, -1.3254138 ,
         -0.8889709 , -1.9

Dimensioanl Transformation

Reshape

In [ ]:
import tensorflow as tf
x=tf.range(96)
x


<tf.Tensor: shape=(96,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95], dtype=int32)>

In [ ]:
x=tf.reshape(x,[2,4,4,3])   # change view to [2,4,4,3] without change storage
x

<tf.Tensor: shape=(2, 4, 4, 3), dtype=int32, numpy=
array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44],
         [45, 46, 47]]],


       [[[48, 49, 50],
         [51, 52, 53],
         [54, 55, 56],
         [57, 58, 59]],

        [[60, 61, 62],
         [63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80],
         [81, 82, 83]],

        [[84, 85, 86],
         [87, 88, 89],
         [90, 91, 92],
         [93, 94, 95]]]], dtype=int32)>

it changes the view of the tensor without changing the storage order.
in tensorflow, we can obtain the dimensions ans shape of a tensor through tensors ndim and shape attribute

In [ ]:
x.ndim,x.shape

(4, TensorShape([2, 4, 4, 3]))

In [ ]:
tf.reshape(x,[2,-1])

<tf.Tensor: shape=(2, 48), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]],
      dtype=int32)>

In [ ]:
tf.reshape(x,[3,-1])  # -1 is used to replace the dimension which should match the prev value

<tf.Tensor: shape=(3, 32), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63],
       [64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]],
      dtype=int32)>

In [ ]:
tf.reshape(x,[2,4,12])

<tf.Tensor: shape=(2, 4, 12), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]],

       [[48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71],
        [72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83],
        [84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]]], dtype=int32)>

In [ ]:
tf.reshape(x,[2,-1,3])

<tf.Tensor: shape=(2, 16, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44],
        [45, 46, 47]],

       [[48, 49, 50],
        [51, 52, 53],
        [54, 55, 56],
        [57, 58, 59],
        [60, 61, 62],
        [63, 64, 65],
        [66, 67, 68],
        [69, 70, 71],
        [72, 73, 74],
        [75, 76, 77],
        [78, 79, 80],
        [81, 82, 83],
        [84, 85, 86],
        [87, 88, 89],
        [90, 91, 92],
        [93, 94, 95]]], dtype=int32)>

Add and Delete Dimensions

In [ ]:
x=tf.random.uniform([28,28],maxval=10,dtype=tf.int32)
x

<tf.Tensor: shape=(28, 28), dtype=int32, numpy=
array([[1, 0, 3, 2, 8, 7, 3, 9, 4, 4, 1, 6, 4, 2, 9, 9, 6, 4, 6, 2, 8, 0,
        1, 1, 1, 6, 7, 1],
       [0, 5, 6, 7, 6, 5, 4, 9, 8, 4, 6, 0, 4, 6, 5, 3, 1, 7, 9, 6, 0, 1,
        7, 3, 9, 3, 0, 1],
       [0, 9, 2, 0, 7, 6, 4, 4, 6, 3, 3, 5, 4, 1, 7, 8, 4, 6, 5, 0, 4, 7,
        5, 3, 0, 8, 5, 3],
       [0, 4, 9, 2, 1, 0, 8, 3, 7, 6, 7, 4, 5, 7, 5, 5, 0, 2, 9, 1, 2, 5,
        1, 1, 3, 5, 7, 0],
       [3, 0, 1, 5, 3, 1, 6, 2, 1, 8, 1, 7, 2, 1, 2, 2, 5, 3, 5, 8, 9, 3,
        0, 0, 9, 9, 3, 6],
       [3, 4, 8, 6, 4, 4, 8, 9, 6, 7, 2, 4, 4, 4, 6, 9, 4, 9, 1, 5, 4, 4,
        6, 5, 9, 5, 2, 7],
       [0, 5, 7, 9, 0, 2, 5, 9, 0, 5, 3, 3, 2, 2, 9, 1, 9, 0, 7, 5, 7, 2,
        0, 1, 8, 4, 9, 6],
       [9, 0, 0, 5, 8, 5, 7, 5, 2, 6, 2, 7, 0, 7, 8, 7, 1, 3, 6, 7, 6, 8,
        1, 3, 1, 2, 0, 3],
       [0, 7, 3, 0, 8, 9, 8, 0, 7, 5, 6, 1, 7, 4, 5, 3, 1, 6, 9, 7, 3, 4,
        1, 1, 5, 9, 0, 4],
       [1, 1, 0, 9, 6, 5, 0, 4, 2, 3, 1, 4,

In [ ]:
x=tf.expand_dims(x,axis=2)
x

<tf.Tensor: shape=(28, 28, 1, 1), dtype=int32, numpy=
array([[[[9]],

        [[9]],

        [[6]],

        [[4]],

        [[7]],

        [[8]],

        [[0]],

        [[4]],

        [[0]],

        [[5]],

        [[7]],

        [[0]],

        [[7]],

        [[8]],

        [[1]],

        [[9]],

        [[5]],

        [[6]],

        [[9]],

        [[2]],

        [[8]],

        [[0]],

        [[6]],

        [[0]],

        [[3]],

        [[0]],

        [[6]],

        [[0]]],


       [[[5]],

        [[5]],

        [[8]],

        [[0]],

        [[3]],

        [[9]],

        [[6]],

        [[1]],

        [[2]],

        [[1]],

        [[2]],

        [[0]],

        [[1]],

        [[9]],

        [[3]],

        [[4]],

        [[6]],

        [[2]],

        [[2]],

        [[2]],

        [[5]],

        [[6]],

        [[6]],

        [[6]],

        [[2]],

        [[5]],

        [[5]],

        [[9]]],


       [[[2]],

        [[3]],

        [[7]],

In [ ]:
x=tf.expand_dims(x,axis=0)
x

<tf.Tensor: shape=(1, 28, 28, 1, 1), dtype=int32, numpy=
array([[[[[9]],

         [[9]],

         [[6]],

         [[4]],

         [[7]],

         [[8]],

         [[0]],

         [[4]],

         [[0]],

         [[5]],

         [[7]],

         [[0]],

         [[7]],

         [[8]],

         [[1]],

         [[9]],

         [[5]],

         [[6]],

         [[9]],

         [[2]],

         [[8]],

         [[0]],

         [[6]],

         [[0]],

         [[3]],

         [[0]],

         [[6]],

         [[0]]],


        [[[5]],

         [[5]],

         [[8]],

         [[0]],

         [[3]],

         [[9]],

         [[6]],

         [[1]],

         [[2]],

         [[1]],

         [[2]],

         [[0]],

         [[1]],

         [[9]],

         [[3]],

         [[4]],

         [[6]],

         [[2]],

         [[2]],

         [[2]],

         [[5]],

         [[6]],

         [[6]],

         [[6]],

         [[2]],

         [[5]],

         [[5]],

      

In [ ]:
x=tf.expand_dims(x,axis=-1)
x

<tf.Tensor: shape=(28, 28, 1), dtype=int32, numpy=
array([[[1],
        [0],
        [3],
        [2],
        [8],
        [7],
        [3],
        [9],
        [4],
        [4],
        [1],
        [6],
        [4],
        [2],
        [9],
        [9],
        [6],
        [4],
        [6],
        [2],
        [8],
        [0],
        [1],
        [1],
        [1],
        [6],
        [7],
        [1]],

       [[0],
        [5],
        [6],
        [7],
        [6],
        [5],
        [4],
        [9],
        [8],
        [4],
        [6],
        [0],
        [4],
        [6],
        [5],
        [3],
        [1],
        [7],
        [9],
        [6],
        [0],
        [1],
        [7],
        [3],
        [9],
        [3],
        [0],
        [1]],

       [[0],
        [9],
        [2],
        [0],
        [7],
        [6],
        [4],
        [4],
        [6],
        [3],
        [3],
        [5],
        [4],
        [1],
        [7],
        [8],
        [

when the axis of tf.expand_dims is positive it means new dimension is inserted before the current dimension and when it is negative new dimension is inserted after the current dimension

In [ ]:
import tensorflow as tf
x=tf.expand_dims(x,axis=0)
x

<tf.Tensor: shape=(1, 28, 28, 1), dtype=int32, numpy=
array([[[[1],
         [0],
         [3],
         [2],
         [8],
         [7],
         [3],
         [9],
         [4],
         [4],
         [1],
         [6],
         [4],
         [2],
         [9],
         [9],
         [6],
         [4],
         [6],
         [2],
         [8],
         [0],
         [1],
         [1],
         [1],
         [6],
         [7],
         [1]],

        [[0],
         [5],
         [6],
         [7],
         [6],
         [5],
         [4],
         [9],
         [8],
         [4],
         [6],
         [0],
         [4],
         [6],
         [5],
         [3],
         [1],
         [7],
         [9],
         [6],
         [0],
         [1],
         [7],
         [3],
         [9],
         [3],
         [0],
         [1]],

        [[0],
         [9],
         [2],
         [0],
         [7],
         [6],
         [4],
         [4],
         [6],
         [3],
         [3],
    

In [ ]:
x=tf.squeeze(x,axis=0)
x

<tf.Tensor: shape=(28, 28, 1), dtype=int32, numpy=
array([[[1],
        [0],
        [3],
        [2],
        [8],
        [7],
        [3],
        [9],
        [4],
        [4],
        [1],
        [6],
        [4],
        [2],
        [9],
        [9],
        [6],
        [4],
        [6],
        [2],
        [8],
        [0],
        [1],
        [1],
        [1],
        [6],
        [7],
        [1]],

       [[0],
        [5],
        [6],
        [7],
        [6],
        [5],
        [4],
        [9],
        [8],
        [4],
        [6],
        [0],
        [4],
        [6],
        [5],
        [3],
        [1],
        [7],
        [9],
        [6],
        [0],
        [1],
        [7],
        [3],
        [9],
        [3],
        [0],
        [1]],

       [[0],
        [9],
        [2],
        [0],
        [7],
        [6],
        [4],
        [4],
        [6],
        [3],
        [3],
        [5],
        [4],
        [1],
        [7],
        [8],
        [

In [ ]:
x=tf.squeeze(x)  #if axis is not mentioned ,dimension 1 is automatically deleted 
x

<tf.Tensor: shape=(28, 28), dtype=int32, numpy=
array([[1, 0, 3, 2, 8, 7, 3, 9, 4, 4, 1, 6, 4, 2, 9, 9, 6, 4, 6, 2, 8, 0,
        1, 1, 1, 6, 7, 1],
       [0, 5, 6, 7, 6, 5, 4, 9, 8, 4, 6, 0, 4, 6, 5, 3, 1, 7, 9, 6, 0, 1,
        7, 3, 9, 3, 0, 1],
       [0, 9, 2, 0, 7, 6, 4, 4, 6, 3, 3, 5, 4, 1, 7, 8, 4, 6, 5, 0, 4, 7,
        5, 3, 0, 8, 5, 3],
       [0, 4, 9, 2, 1, 0, 8, 3, 7, 6, 7, 4, 5, 7, 5, 5, 0, 2, 9, 1, 2, 5,
        1, 1, 3, 5, 7, 0],
       [3, 0, 1, 5, 3, 1, 6, 2, 1, 8, 1, 7, 2, 1, 2, 2, 5, 3, 5, 8, 9, 3,
        0, 0, 9, 9, 3, 6],
       [3, 4, 8, 6, 4, 4, 8, 9, 6, 7, 2, 4, 4, 4, 6, 9, 4, 9, 1, 5, 4, 4,
        6, 5, 9, 5, 2, 7],
       [0, 5, 7, 9, 0, 2, 5, 9, 0, 5, 3, 3, 2, 2, 9, 1, 9, 0, 7, 5, 7, 2,
        0, 1, 8, 4, 9, 6],
       [9, 0, 0, 5, 8, 5, 7, 5, 2, 6, 2, 7, 0, 7, 8, 7, 1, 3, 6, 7, 6, 8,
        1, 3, 1, 2, 0, 3],
       [0, 7, 3, 0, 8, 9, 8, 0, 7, 5, 6, 1, 7, 4, 5, 3, 1, 6, 9, 7, 3, 4,
        1, 1, 5, 9, 0, 4],
       [1, 1, 0, 9, 6, 5, 0, 4, 2, 3, 1, 4,

Changing the view ,adding or deleting the dimension, will not affect storage of the tensor wheras view of the tensor is changed
By swappping the dimesnion using tf.transpose() both the storage order and the view of the tensor is changed

In [ ]:
x=tf.random.normal([2,32,32,3])
x

<tf.Tensor: shape=(2, 32, 32, 3), dtype=float32, numpy=
array([[[[ 0.6267385 , -1.3100661 ,  0.5740053 ],
         [ 1.168185  ,  0.5855046 ,  1.6084123 ],
         [ 0.07822688,  0.7392037 , -0.77889705],
         ...,
         [ 0.10951065,  1.3616478 , -0.88022214],
         [ 0.81346023, -1.2138615 ,  0.8808858 ],
         [-0.03863867, -0.38131693,  0.1221128 ]],

        [[-0.5298716 , -0.52536166,  1.2177653 ],
         [-1.5249207 ,  0.55313754,  0.23279284],
         [ 0.38009927,  2.5822198 , -1.9491683 ],
         ...,
         [ 1.7821572 ,  0.88270766,  0.2596013 ],
         [-0.4536142 ,  0.59438634, -0.15521418],
         [ 0.6915874 , -1.3753988 ,  0.5702232 ]],

        [[-0.07988739, -0.15541366,  0.22043994],
         [ 1.1331524 ,  0.01700244, -0.86937803],
         [-1.8335358 , -0.06405698,  1.1962659 ],
         ...,
         [ 0.9042704 ,  0.26432732,  1.0790795 ],
         [ 0.7373326 , -0.11567427, -0.77761596],
         [ 0.46398345, -2.3084106 ,  1.9118435 ]

In [ ]:
tf.transpose(x,perm=[0,3,1,2]) #swap dimension

<tf.Tensor: shape=(2, 3, 32, 32), dtype=float32, numpy=
array([[[[ 0.6267385 ,  1.168185  ,  0.07822688, ...,  0.10951065,
           0.81346023, -0.03863867],
         [-0.5298716 , -1.5249207 ,  0.38009927, ...,  1.7821572 ,
          -0.4536142 ,  0.6915874 ],
         [-0.07988739,  1.1331524 , -1.8335358 , ...,  0.9042704 ,
           0.7373326 ,  0.46398345],
         ...,
         [ 0.6750835 ,  0.12937315,  0.9905852 , ..., -1.3419055 ,
          -0.6711667 , -1.0062085 ],
         [ 1.0321414 ,  0.24780838, -2.8048282 , ...,  0.8435495 ,
           1.1922003 ,  0.76757157],
         [-0.7629792 ,  1.719255  , -1.1677521 , ..., -0.68040806,
           0.4106225 ,  0.38829893]],

        [[-1.3100661 ,  0.5855046 ,  0.7392037 , ...,  1.3616478 ,
          -1.2138615 , -0.38131693],
         [-0.52536166,  0.55313754,  2.5822198 , ...,  0.88270766,
           0.59438634, -1.3753988 ],
         [-0.15541366,  0.01700244, -0.06405698, ...,  0.26432732,
          -0.11567427, -2.308

In [ ]:
tf.transpose(x,perm=[0,2,1,3])

<tf.Tensor: shape=(2, 32, 32, 3), dtype=float32, numpy=
array([[[[ 0.6267385 , -1.3100661 ,  0.5740053 ],
         [-0.5298716 , -0.52536166,  1.2177653 ],
         [-0.07988739, -0.15541366,  0.22043994],
         ...,
         [ 0.6750835 ,  1.7378927 ,  1.3334074 ],
         [ 1.0321414 , -0.45917907,  0.13482256],
         [-0.7629792 , -1.9915979 , -0.8136038 ]],

        [[ 1.168185  ,  0.5855046 ,  1.6084123 ],
         [-1.5249207 ,  0.55313754,  0.23279284],
         [ 1.1331524 ,  0.01700244, -0.86937803],
         ...,
         [ 0.12937315,  0.01018187, -0.3618228 ],
         [ 0.24780838,  1.6775892 ,  0.33982265],
         [ 1.719255  ,  0.90000457, -1.3851126 ]],

        [[ 0.07822688,  0.7392037 , -0.77889705],
         [ 0.38009927,  2.5822198 , -1.9491683 ],
         [-1.8335358 , -0.06405698,  1.1962659 ],
         ...,
         [ 0.9905852 , -1.2605715 , -1.0831442 ],
         [-2.8048282 ,  0.38756308,  0.10157315],
         [-1.1677521 ,  0.5972193 ,  0.16483316]

Copy Data

After inserting a new dimesnion we may want to copy data on the new dimesnion to meet the requiremenets of subsequent calculations.

In [ ]:
b=tf.constant([1,2])
b

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
b=tf.expand_dims(b,axis=0)
b

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[1, 2]], dtype=int32)>

In [ ]:
b=tf.tile(b,multiples=[2,1])
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [1, 2]], dtype=int32)>

In [ ]:
b=tf.tile(b,multiples=[1,3])
b

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[1, 2, 1, 2, 1, 2],
       [1, 2, 1, 2, 1, 2]], dtype=int32)>

In [ ]:
a=tf.range(4)


In [ ]:
tf.reshape(a,[2,2])


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3], dtype=int32)>

Broadcasting


In [ ]:
a=tf.random.normal([2,2,2])
a

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[0.02745864, 0.85406536],
        [1.1734889 , 0.76752293]],

       [[0.37126622, 0.33470678],
        [1.9601504 , 0.43019128]]], dtype=float32)>

In [ ]:
x=tf.random.normal([2,4])

In [ ]:
w=tf.random.normal([4,3])

In [ ]:
b=tf.random.normal([3])
b

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 2.1084447 , -0.20533893, -0.69502044], dtype=float32)>

In [ ]:
x@w

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.13573134,  1.1672724 ,  1.6387349 ],
       [-0.98941076,  2.945227  , -0.31997883]], dtype=float32)>

In [ ]:
y=x@w+b
y

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.9727134,  0.9619335,  0.9437145],
       [ 1.1190339,  2.739888 , -1.0149993]], dtype=float32)>

In [ ]:
x*w

InvalidArgumentError: ignored

create a matrix a for normal distribution with 32 rows and 1 col using broadcast function expand matrix a to 4 dimensions(2,32,32,3)

In [ ]:
x=tf.random.normal([32,1])
x

<tf.Tensor: shape=(32, 1), dtype=float32, numpy=
array([[-0.76077294],
       [ 1.3177781 ],
       [-0.52085835],
       [-1.2614697 ],
       [-1.1240125 ],
       [ 0.90111345],
       [-0.94854784],
       [ 0.94516224],
       [-0.19591114],
       [ 0.7451182 ],
       [ 1.430911  ],
       [-1.2147669 ],
       [-1.1550188 ],
       [-0.7119527 ],
       [-0.5152413 ],
       [-0.78528   ],
       [-1.3283738 ],
       [-1.2450895 ],
       [ 0.34426415],
       [ 1.0690515 ],
       [-0.08215357],
       [ 0.53697455],
       [-0.2660718 ],
       [-0.9662587 ],
       [-0.27012697],
       [ 0.62233114],
       [ 0.95788556],
       [ 1.5323628 ],
       [ 0.50132984],
       [ 0.3622922 ],
       [-2.534719  ],
       [ 0.8303767 ]], dtype=float32)>

In [ ]:
tf.broadcast_to(x,[2,32,32,3])


<tf.Tensor: shape=(2, 32, 32, 3), dtype=float32, numpy=
array([[[[-0.76077294, -0.76077294, -0.76077294],
         [ 1.3177781 ,  1.3177781 ,  1.3177781 ],
         [-0.52085835, -0.52085835, -0.52085835],
         ...,
         [ 0.3622922 ,  0.3622922 ,  0.3622922 ],
         [-2.534719  , -2.534719  , -2.534719  ],
         [ 0.8303767 ,  0.8303767 ,  0.8303767 ]],

        [[-0.76077294, -0.76077294, -0.76077294],
         [ 1.3177781 ,  1.3177781 ,  1.3177781 ],
         [-0.52085835, -0.52085835, -0.52085835],
         ...,
         [ 0.3622922 ,  0.3622922 ,  0.3622922 ],
         [-2.534719  , -2.534719  , -2.534719  ],
         [ 0.8303767 ,  0.8303767 ,  0.8303767 ]],

        [[-0.76077294, -0.76077294, -0.76077294],
         [ 1.3177781 ,  1.3177781 ,  1.3177781 ],
         [-0.52085835, -0.52085835, -0.52085835],
         ...,
         [ 0.3622922 ,  0.3622922 ,  0.3622922 ],
         [-2.534719  , -2.534719  , -2.534719  ],
         [ 0.8303767 ,  0.8303767 ,  0.8303767 ]

In [ ]:
a=tf.random.normal([2,32,32,1])

In [ ]:
b=tf.random.normal([32,32])

In [ ]:
a+b

<tf.Tensor: shape=(2, 32, 32, 32), dtype=float32, numpy=
array([[[[-1.4965656e+00, -7.5739765e-01,  4.4424689e-01, ...,
           1.7758386e+00,  1.1492583e+00,  1.5141222e-01],
         [ 8.5314846e-01,  1.1021940e+00, -3.3691168e-02, ...,
           1.4060218e+00,  3.6862630e-01,  1.5134808e+00],
         [-1.9574611e+00, -5.9288263e-01, -7.9073304e-01, ...,
          -1.7983714e-01, -4.0190500e-01, -4.1687161e-02],
         ...,
         [-2.0160968e+00, -1.8325195e+00, -1.5998416e+00, ...,
          -2.3800356e+00,  8.1194419e-01, -2.0631227e+00],
         [ 1.9963223e-01, -1.1988672e+00,  3.4717333e-01, ...,
          -6.3161600e-01,  5.6936282e-01, -2.0843370e+00],
         [-3.2634482e-01, -1.5302165e+00, -9.4219959e-01, ...,
          -4.9994525e-01, -1.0089771e+00, -3.4030551e-01]],

        [[-1.5996468e+00, -8.6047888e-01,  3.4116566e-01, ...,
           1.6727574e+00,  1.0461770e+00,  4.8331022e-02],
         [-1.0607570e+00, -8.1171155e-01, -1.9475967e+00, ...,
          

In [ ]:
a-b

<tf.Tensor: shape=(2, 32, 32, 32), dtype=float32, numpy=
array([[[[ 1.39129400e+00,  6.52126074e-01, -5.49518466e-01, ...,
          -1.88111019e+00, -1.25452983e+00, -2.56683826e-01],
         [ 1.32369852e+00,  1.07465303e+00,  2.21053815e+00, ...,
           7.70825088e-01,  1.80822062e+00,  6.63366199e-01],
         [ 1.58261609e+00,  2.18037456e-01,  4.15887892e-01, ...,
          -1.95008010e-01,  2.70598531e-02, -3.33157986e-01],
         ...,
         [ 3.14452052e-02, -1.52132094e-01, -3.84810090e-01, ...,
           3.95384014e-01, -2.79659581e+00,  7.84710050e-02],
         [-1.35940003e+00,  3.90994549e-02, -1.50694108e+00, ...,
          -5.28151751e-01, -1.72913051e+00,  9.24569190e-01],
         [-7.40808964e-01,  4.63062584e-01, -1.24954224e-01, ...,
          -5.67208529e-01, -5.81767261e-02, -7.26848304e-01]],

        [[ 1.28821278e+00,  5.49044847e-01, -6.52599692e-01, ...,
          -1.98419142e+00, -1.35761106e+00, -3.59765023e-01],
         [-5.90206981e-01, -8.3

In [ ]:
a*b

<tf.Tensor: shape=(2, 32, 32, 32), dtype=float32, numpy=
array([[[[ 7.60024041e-02,  3.70957069e-02, -2.61538196e-02, ...,
          -9.62432176e-02, -6.32626563e-02, -1.07402317e-02],
         [-2.56078839e-01,  1.49881234e-02, -1.22133601e+00, ...,
           3.45681548e-01, -7.83444166e-01,  4.62642342e-01],
         [ 3.31745178e-01,  7.59923607e-02,  1.13073997e-01, ...,
          -1.42168184e-03,  4.01988477e-02, -2.73141060e-02],
         ...,
         [ 1.01591444e+00,  8.33745956e-01,  6.02853596e-01, ...,
           1.37706029e+00, -1.79042375e+00,  1.06257939e+00],
         [-4.52028811e-01,  3.58938456e-01, -5.37585497e-01, ...,
           2.99986303e-02, -6.66429639e-01,  8.72408092e-01],
         [-1.10574253e-01,  5.31783819e-01,  2.18031630e-01, ...,
          -1.79450680e-02,  2.53662556e-01, -1.03125162e-01]],

        [[ 2.24844411e-01,  1.09743401e-01, -7.73730800e-02, ...,
          -2.84724563e-01, -1.87155336e-01, -3.17737460e-02],
         [ 1.94215298e-01, -1.1

In [ ]:
a/b

<tf.Tensor: shape=(2, 32, 32, 32), dtype=float32, numpy=
array([[[[ 3.64531614e-02,  7.46859387e-02, -1.05932057e-01, ...,
          -2.87867319e-02, -4.37940471e-02, -2.57957935e-01],
         [-4.62617540e+00,  7.90402908e+01, -9.69975293e-01, ...,
           3.42704344e+00, -1.51212525e+00,  2.56065130e+00],
         [ 1.05886154e-01,  4.62246746e-01,  3.10656935e-01, ...,
          -2.47082157e+01,  8.73836517e-01, -1.28604686e+00],
         ...,
         [ 9.69284952e-01,  1.18106782e+00,  1.63341582e+00, ...,
           7.15081632e-01, -5.49987435e-01,  9.26717162e-01],
         [-7.43902385e-01,  9.36832786e-01, -6.25510335e-01, ...,
           1.12093554e+01, -5.04577398e-01,  3.85444969e-01],
         [-2.57477927e+00,  5.35376072e-01,  1.30579364e+00, ...,
          -1.58653250e+01,  1.12237418e+00, -2.76076484e+00]],

        [[ 1.07842505e-01,  2.20949814e-01, -3.13387871e-01, ...,
          -8.51622522e-02, -1.29559681e-01, -7.63139009e-01],
         [ 3.50858331e+00, -5.9

automatic broadcasting will be done for +, -,*,/

power operations

In [ ]:
x=tf.range(4)
tf.pow(x,3)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 0,  1,  8, 27], dtype=int32)>

In [ ]:
x**2

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 4, 9], dtype=int32)>

In [ ]:
x=tf.constant([1.,4.,9,])
x**(0.5)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [ ]:
x=tf.exp(3.)
x

<tf.Tensor: shape=(), dtype=float32, numpy=20.085537>

In [ ]:
tf.math.log(X)

NameError: ignored

In [ ]:
import tensorflow as tf
x=tf.range(9)
x


<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [ ]:
tf.minimum(tf.maximum(x,2),7)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([2, 2, 2, 3, 4, 5, 6, 7, 7], dtype=int32)>

In [ ]:
a=tf.random.normal([10,35,4])
b=tf.random.normal([10,35,4])
tf.concat([a,b],axis=2)

<tf.Tensor: shape=(10, 35, 8), dtype=float32, numpy=
array([[[-0.5922853 ,  0.6964854 , -0.9514699 , ..., -0.2260057 ,
         -0.94365275, -1.2250569 ],
        [ 0.531183  , -0.7893213 ,  1.1284302 , ..., -0.9560249 ,
         -0.68095094, -1.7225633 ],
        [-0.34964755, -0.7008227 ,  0.37440288, ..., -0.2910164 ,
          0.7629886 , -1.6585348 ],
        ...,
        [-0.21347782, -0.13140444,  1.3101534 , ...,  0.46837345,
          0.7764077 , -0.87910604],
        [ 0.46666676,  0.20527482,  0.27171785, ...,  0.7553799 ,
         -1.5840589 , -1.126297  ],
        [ 1.5489471 ,  1.0659952 ,  0.22522579, ..., -0.7857731 ,
         -0.9729625 ,  1.2116953 ]],

       [[-0.14752921,  0.08062007, -0.05103132, ..., -3.0279431 ,
         -0.3784792 , -0.94258565],
        [ 1.7245657 ,  0.01029139,  0.6119654 , ..., -0.523334  ,
          1.1273878 ,  0.27439708],
        [-0.71673095, -1.5198516 ,  0.06674293, ..., -2.1937299 ,
         -0.1539351 , -0.9841371 ],
        ...,
 

In [ ]:
a=tf.random.normal([10,35,4])
b=tf.random.normal([10,35,4])
tf.concat([a,b],axis=1)

<tf.Tensor: shape=(10, 70, 4), dtype=float32, numpy=
array([[[ 0.49460638, -0.35237974, -0.37143013, -0.5693829 ],
        [ 2.399418  ,  0.48533148, -0.4272737 , -0.5210291 ],
        [-1.1886414 , -1.8643719 , -0.39703748, -0.64290524],
        ...,
        [-0.9247077 ,  2.5528958 , -0.70523065, -0.47262242],
        [ 0.40352184, -2.1561463 ,  0.57226837,  0.55728644],
        [-0.8819151 , -1.423444  , -1.314271  ,  1.1200923 ]],

       [[-1.4748678 ,  0.7393456 ,  0.76200753, -1.3995689 ],
        [-2.3520913 , -0.7946101 ,  1.4294404 ,  0.5688116 ],
        [-0.77472246,  0.7994498 , -0.7885786 , -0.4020706 ],
        ...,
        [ 0.888219  , -1.6356189 , -0.38561183, -0.9046869 ],
        [-0.0428982 ,  1.3012118 , -1.2166967 , -2.133349  ],
        [-0.0525795 ,  0.02541221,  0.4534084 ,  0.07149811]],

       [[-0.4107576 , -0.5364105 , -1.3517716 , -0.38497296],
        [ 0.32041124,  0.82154316,  2.1108782 , -0.06637643],
        [ 0.5821915 ,  0.9548279 , -0.98431456, -

In [ ]:
a=tf.random.normal([4,20,3]) 
b=tf.random.normal([6,20,4])
tf.concat([a,b],axis=2)

InvalidArgumentError: ignored

The non merging dimensions hsould be same to avoid errors.

In [ ]:
a=tf.random.normal([35,8])
b=tf.random.normal([35,8])
tf.stack([a,b],axis=1)

<tf.Tensor: shape=(35, 2, 8), dtype=float32, numpy=
array([[[ 8.95675898e-01,  6.77354693e-01, -4.80002493e-01,
         -1.15770495e+00,  2.30092692e+00,  5.42967141e-01,
          5.47806203e-01,  2.01719141e+00],
        [-8.15793812e-01,  9.04693067e-01,  8.69721115e-01,
         -1.05820262e+00, -1.37065375e+00, -7.57585049e-01,
         -9.05638278e-01,  1.10145003e-01]],

       [[ 4.84186381e-01,  1.10190845e+00, -2.46103907e+00,
         -1.95194912e+00,  1.31614149e-01, -6.25676095e-01,
         -2.65801251e-01, -4.62718345e-02],
        [-1.12386239e+00, -4.13832128e-01,  4.27725345e-01,
          9.93339896e-01,  1.60511300e-01,  7.24230409e-01,
         -2.56657153e-01, -1.21260893e+00]],

       [[-1.17324114e+00, -6.17451787e-01,  2.82627851e-01,
          1.17839158e+00, -2.73644328e-01, -1.00234258e+00,
          1.91381383e+00,  5.16827226e-01],
        [-2.69434392e-01,  7.71297440e-02, -1.71149719e+00,
         -6.70960724e-01, -9.38662350e-01, -1.07107408e-01,
    

In [ ]:
x=tf.random.normal([10,35,8])
res=tf.split(x,num_or_size_splits=10,axis=0)
len(res)

10

In [ ]:
x=tf.random.normal([10,35,8])
res=tf.split(x,num_or_size_splits=[4,2,2,2],axis=0)
len(res)

4

In [ ]:
res[0]

<tf.Tensor: shape=(4, 35, 8), dtype=float32, numpy=
array([[[ 0.08207136,  0.62364894, -1.5490421 , ..., -1.8473022 ,
         -1.3811318 ,  0.6545969 ],
        [ 0.79422945, -0.26439458, -0.60233396, ...,  0.31402305,
         -1.2975518 , -1.0097402 ],
        [-0.8857436 ,  0.53331655, -0.87574595, ...,  0.36860693,
          0.19909418,  1.3960052 ],
        ...,
        [-0.8566448 , -0.29173028, -1.6102388 , ...,  0.77531606,
         -0.9026202 , -1.6360055 ],
        [-1.6177841 , -0.4342264 ,  0.7349512 , ...,  0.94913197,
          2.2430446 , -0.6373483 ],
        [ 0.65481967,  1.2205017 ,  0.1804444 , ..., -0.44493207,
         -1.6403356 ,  1.9491414 ]],

       [[-2.1798189 , -0.9755426 , -0.25241768, ...,  2.6429145 ,
          0.71469665, -1.9155515 ],
        [ 0.2777934 , -1.820237  , -0.8490916 , ..., -0.70463854,
          0.60371023,  0.14165987],
        [-0.20278718, -0.8991856 , -0.4140047 , ...,  1.0376835 ,
          0.5127576 ,  0.63203734],
        ...,
  

In [ ]:
x=tf.random.normal([10,35,8])
res=tf.unstack(x,axis=0)
len(res)

10

Advanced operations

In [ ]:
import tensorflow as tf
x=tf.random.uniform([4,35,8],maxval=100,dtype=tf.int32)
x

<tf.Tensor: shape=(4, 35, 8), dtype=int32, numpy=
array([[[90, 23, 91, ..., 45, 67, 26],
        [ 1,  3, 78, ...,  5, 18, 59],
        [20, 35,  4, ...,  5, 58, 34],
        ...,
        [73,  2, 71, ..., 59, 57, 27],
        [76, 38, 49, ..., 86, 27, 60],
        [54, 58, 37, ..., 17, 91, 88]],

       [[11, 19, 94, ..., 34, 85, 39],
        [65, 57, 91, ..., 44, 55, 13],
        [45, 71, 34, ..., 83,  9, 24],
        ...,
        [57, 50, 66, ..., 60,  5, 52],
        [90, 13, 28, ..., 60, 91, 76],
        [37, 11, 43, ..., 53, 79,  6]],

       [[56, 87, 29, ..., 50, 91, 59],
        [67, 72, 54, ..., 41, 21, 32],
        [ 1, 30, 74, ..., 24, 77, 27],
        ...,
        [10, 42, 51, ..., 84, 81, 64],
        [77, 79, 53, ..., 41, 48, 80],
        [56, 97, 19, ..., 44, 74, 91]],

       [[80, 37, 68, ..., 55,  6, 70],
        [73, 84, 68, ..., 81, 35, 57],
        [23, 11,  5, ..., 86, 83, 32],
        ...,
        [92, 37, 77, ..., 58, 20, 69],
        [91, 34, 83, ..., 94, 10, 

In [ ]:
tf.gather(x,[0,3,8,11,12,26],axis=1)

<tf.Tensor: shape=(4, 6, 8), dtype=int32, numpy=
array([[[27, 32, 15, 26, 95, 75, 52, 95],
        [60, 60, 88, 46, 35,  6, 85, 91],
        [41, 63, 10, 57, 79, 82, 25, 24],
        [44, 33, 15, 21, 83, 20, 22,  4],
        [98, 42, 36, 16, 19, 42, 49, 98],
        [92, 37, 46,  6, 13, 78, 16, 54]],

       [[71, 64, 48, 32, 84, 27, 86, 96],
        [12, 70, 21, 63, 77, 43, 14, 71],
        [56, 87, 85, 43, 89, 57, 72, 83],
        [99, 60, 23, 60, 53, 85, 27, 94],
        [52, 95, 28,  8, 48, 14, 55,  7],
        [64, 64, 29, 16, 90, 56, 70,  4]],

       [[99, 90, 62, 95, 76, 67, 72,  6],
        [ 5, 11, 34, 80, 57, 75, 54, 34],
        [32, 24, 37, 31, 49, 68, 90, 28],
        [44, 20, 60, 44, 19, 22, 64, 96],
        [52, 68, 92,  5, 59, 28, 21, 25],
        [90,  7,  9, 46, 43, 34, 89, 64]],

       [[44, 62, 72, 20, 13, 66, 35, 32],
        [53, 27, 42, 19, 73, 10, 79, 44],
        [94, 64, 59,  4, 36, 47, 51,  7],
        [92, 51, 45, 27, 11, 63, 88, 39],
        [72, 90,  7, 

In [ ]:
tf.gather(x,[2,4],axis=2) # collect the grades of 3rd and 5th subjects of all students

<tf.Tensor: shape=(4, 35, 2), dtype=int32, numpy=
array([[[15, 95],
        [ 1, 87],
        [74, 16],
        [88, 35],
        [18, 45],
        [26, 30],
        [ 2, 55],
        [97,  6],
        [10, 79],
        [55, 23],
        [75, 58],
        [15, 83],
        [36, 19],
        [19, 95],
        [31, 49],
        [48, 47],
        [ 7, 73],
        [97,  0],
        [25, 23],
        [68, 42],
        [42, 41],
        [96, 53],
        [93, 42],
        [ 2, 55],
        [13, 90],
        [63, 72],
        [46, 13],
        [18, 98],
        [18, 77],
        [ 7, 42],
        [95, 52],
        [90, 88],
        [33, 53],
        [94, 33],
        [40, 80]],

       [[48, 84],
        [56, 41],
        [96, 62],
        [21, 77],
        [60,  3],
        [93, 15],
        [35, 16],
        [37, 88],
        [85, 89],
        [49, 35],
        [36, 98],
        [23, 53],
        [28, 48],
        [70, 50],
        [46, 83],
        [84, 48],
        [79, 15],
        [44,

In [ ]:
students=tf.gather(x,[1,2],axis=0) # collect data for class 2 ans 3
students

<tf.Tensor: shape=(2, 35, 8), dtype=int32, numpy=
array([[[71, 64, 48, 32, 84, 27, 86, 96],
        [96, 71, 56,  1, 41, 61,  4, 57],
        [61,  0, 96, 61, 62, 31, 58, 66],
        [12, 70, 21, 63, 77, 43, 14, 71],
        [62, 35, 60,  4,  3, 71, 89, 97],
        [48, 35, 93, 20, 15, 27, 97, 64],
        [88, 56, 35, 55, 16, 16, 61, 98],
        [ 5, 75, 37, 50, 88, 63, 97, 68],
        [56, 87, 85, 43, 89, 57, 72, 83],
        [58, 87, 49, 72, 35, 51,  1, 98],
        [21, 75, 36, 59, 98, 86, 22, 42],
        [99, 60, 23, 60, 53, 85, 27, 94],
        [52, 95, 28,  8, 48, 14, 55,  7],
        [ 7, 75, 70,  8, 50,  2, 59, 98],
        [77, 51, 46, 85, 83,  8, 45,  2],
        [99, 11, 84, 83, 48, 86, 37, 60],
        [73, 19, 79, 60, 15, 11, 76, 18],
        [45,  9, 44, 93, 12, 73, 24, 32],
        [ 1, 33, 29, 84, 70, 12,  9, 61],
        [73, 53, 33, 38,  4, 36,  0, 66],
        [54, 88, 98, 74, 37, 63,  0, 84],
        [76, 67, 62,  7, 57, 66, 19, 20],
        [99, 89, 30, 40, 3

In [ ]:
tf.gather(students,[2,3,5,26],axis=1)

<tf.Tensor: shape=(2, 4, 8), dtype=int32, numpy=
array([[[61,  0, 96, 61, 62, 31, 58, 66],
        [12, 70, 21, 63, 77, 43, 14, 71],
        [48, 35, 93, 20, 15, 27, 97, 64],
        [64, 64, 29, 16, 90, 56, 70,  4]],

       [[19, 95, 85, 76,  1, 32, 17, 74],
        [ 5, 11, 34, 80, 57, 75, 54, 34],
        [85, 50, 63, 64, 34, 72, 85, 89],
        [90,  7,  9, 46, 43, 34, 89, 64]]], dtype=int32)>

In [ ]:
a=tf.gather(students,[1,2],axis=1)
a

<tf.Tensor: shape=(2, 2, 8), dtype=int32, numpy=
array([[[96, 71, 56,  1, 41, 61,  4, 57],
        [61,  0, 96, 61, 62, 31, 58, 66]],

       [[30, 15, 55, 25, 38, 96, 25, 72],
        [19, 95, 85, 76,  1, 32, 17, 74]]], dtype=int32)>

In [ ]:
x[1,1]

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([96, 71, 56,  1, 41, 61,  4, 57], dtype=int32)>

In [ ]:
tf.stack([x[1,1],x[2,2],x[3,3]],axis=0)

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[96, 71, 56,  1, 41, 61,  4, 57],
       [19, 95, 85, 76,  1, 32, 17, 74],
       [53, 27, 42, 19, 73, 10, 79, 44]], dtype=int32)>

In [ ]:
a=tf.range(8)

In [ ]:
a=tf.reshape(a,[4,2])
a

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]], dtype=int32)>

In [ ]:
tf.gather(a,[3,1,0,2],axis=0)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[6, 7],
       [2, 3],
       [0, 1],
       [4, 5]], dtype=int32)>

In [ ]:
import tensorflow as tf
tf.gather_nd(x,[[1,1],[2,2],[3,3]])

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[96, 71, 56,  1, 41, 61,  4, 57],
       [19, 95, 85, 76,  1, 32, 17, 74],
       [53, 27, 42, 19, 73, 10, 79, 44]], dtype=int32)>

In [ ]:
import tensorflow as tf
tf.boolean_mask(x,mask=[True,False,False,True],axis=0)

<tf.Tensor: shape=(2, 35, 8), dtype=int32, numpy=
array([[[90, 23, 91, 86, 83, 45, 67, 26],
        [ 1,  3, 78, 76, 60,  5, 18, 59],
        [20, 35,  4, 87, 22,  5, 58, 34],
        [ 4, 21, 64, 54, 26, 50, 89,  2],
        [62, 47, 73,  3,  6, 63, 16, 84],
        [70, 80, 94, 69, 53, 97, 28, 70],
        [97, 88, 49, 77, 99, 56, 52, 78],
        [37, 28, 82, 90, 90, 21, 22, 43],
        [49, 64, 96, 45, 61, 42, 12, 67],
        [11, 39, 32,  8, 64, 75, 21, 83],
        [53, 84, 39, 92, 30, 73, 92, 69],
        [99, 40, 65, 17, 64,  0, 67, 59],
        [ 2, 27, 70, 37,  4, 50, 61,  4],
        [39, 54, 38,  9, 39, 71,  2, 45],
        [86, 85, 92, 25, 48, 94, 26, 51],
        [30, 18, 36, 22, 93, 59,  2, 79],
        [59, 23, 69, 34, 73, 67, 43, 98],
        [30, 91,  3, 31, 42, 52, 64, 37],
        [20, 36, 23, 20, 78, 36, 73,  8],
        [75, 30, 43, 12, 64, 10, 71, 66],
        [67, 60, 51, 19, 54, 64, 65, 35],
        [14, 68, 53,  4,  5, 48, 36, 11],
        [31, 40, 69, 49, 8

In [ ]:
x=tf.random.uniform([2,3,8],maxval=100,dtype=tf.int32)
tf.gather_nd(x,[[0,0],[0,1],[1,1],[1,2]])

<tf.Tensor: shape=(4, 8), dtype=int32, numpy=
array([[29, 15, 29, 34, 18, 88, 24, 81],
       [75, 12,  9, 28, 43, 92, 85,  8],
       [52,  5,  0, 70, 25, 36, 45, 49],
       [16, 64, 37, 18, 21, 22, 43, 69]], dtype=int32)>

In [ ]:
a=tf.ones([3,3])
a

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
b=tf.zeros([3,3])
b

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
cond=tf.constant([[True,False,False],[False,True,False],[True,True,False]])
tf.where(cond,a,b)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 1., 0.]], dtype=float32)>

In [ ]:
cond

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True, False, False],
       [False,  True, False],
       [ True,  True, False]])>

In [ ]:
tf.where(cond)

<tf.Tensor: shape=(4, 2), dtype=int64, numpy=
array([[0, 0],
       [1, 1],
       [2, 0],
       [2, 1]])>

In [ ]:
x=tf.random.normal([3,3])
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.2859613 , -0.36632952,  0.9498124 ],
       [ 0.15881462,  0.9500719 ,  0.51889616],
       [-1.1461492 ,  2.5056467 , -0.7228673 ]], dtype=float32)>

In [ ]:
mask=x>0
mask

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[False, False,  True],
       [ True,  True,  True],
       [False,  True, False]])>

In [ ]:
indices=tf.where(mask)
indices

<tf.Tensor: shape=(5, 2), dtype=int64, numpy=
array([[0, 2],
       [1, 0],
       [1, 1],
       [1, 2],
       [2, 1]])>

In [ ]:
tf.gather_nd(x,indices)

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([0.9498124 , 0.15881462, 0.9500719 , 0.51889616, 2.5056467 ],
      dtype=float32)>

In [ ]:
tf.boolean_mask(x,mask)

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([0.9498124 , 0.15881462, 0.9500719 , 0.51889616, 2.5056467 ],
      dtype=float32)>